// Copyright 2026 LgThx. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GlobalShader.h"
#include "ShaderParameterStruct.h"
#include "RenderGraphResources.h"
#include "FleshRingDebugTypes.h"

/**
 * FFleshRingDebugPointVS - Debug Point Vertex Shader
 * Vertex shader for GPU circular debug point rendering
 *
 * Transforms debug points generated by TightnessCS into screen-space billboards.
 * Instanced rendering: 4 vertices per quad, N instances (points).
 */
class FFleshRingDebugPointVS : public FGlobalShader
{
public:
    DECLARE_GLOBAL_SHADER(FFleshRingDebugPointVS);
    SHADER_USE_PARAMETER_STRUCT(FFleshRingDebugPointVS, FGlobalShader);

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        // Input: Debug points from TightnessCS
        // Using RHI SRV directly (workaround for RDG SRV binding issues)
        SHADER_PARAMETER_SRV(StructuredBuffer<FFleshRingDebugPoint>, DebugPoints)

        // View-Projection matrix for world to clip space transformation
        SHADER_PARAMETER(FMatrix44f, ViewProjectionMatrix)

        // 1/ViewportSize for pixel to NDC conversion
        SHADER_PARAMETER(FVector2f, InvViewportSize)

        // Base point size in pixels
        SHADER_PARAMETER(float, PointSizeBase)

        // Additional size based on Influence value
        SHADER_PARAMETER(float, PointSizeInfluence)

        // Color mode: 0 = Tightness (Blue->Green->Red), 1 = Bulge (Cyan->Magenta)
        SHADER_PARAMETER(uint32, ColorMode)
    END_SHADER_PARAMETER_STRUCT()

    static bool ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters)
    {
        // Require SM5 for structured buffer support
        return IsFeatureLevelSupported(Parameters.Platform, ERHIFeatureLevel::SM5);
    }
};

/**
 * FFleshRingDebugPointPS - Debug Point Pixel Shader
 * Pixel shader for GPU circular debug point rendering
 *
 * Renders circular points with influence-based color gradient:
 * Blue (0) -> Green (0.5) -> Red (1)
 */
class FFleshRingDebugPointPS : public FGlobalShader
{
public:
    DECLARE_GLOBAL_SHADER(FFleshRingDebugPointPS);
    SHADER_USE_PARAMETER_STRUCT(FFleshRingDebugPointPS, FGlobalShader);

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        // Buffer for RDG resource tracking (ensures RDG performs resource state transitions correctly)
        SHADER_PARAMETER_RDG_BUFFER_SRV(StructuredBuffer<FFleshRingDebugPoint>, DebugPointsRDG)

        // Bitmask array for Ring visibility filtering (supports unlimited Rings)
        // Each uint32 element is a visibility bitmask for 32 Rings
        // Element[0] = Ring 0-31, Element[1] = Ring 32-63, ...
        SHADER_PARAMETER_RDG_BUFFER_SRV(StructuredBuffer<uint>, RingVisibilityMask)
        SHADER_PARAMETER(uint32, NumVisibilityMaskElements)

        // Outline opacity (0.0 = no outline, 1.0 = full outline)
        SHADER_PARAMETER(float, DebugPointOutlineOpacity)

        // Render target binding for output
        RENDER_TARGET_BINDING_SLOTS()
    END_SHADER_PARAMETER_STRUCT()

    static bool ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters)
    {
        // Require SM5 for consistent rendering
        return IsFeatureLevelSupported(Parameters.Platform, ERHIFeatureLevel::SM5);
    }
};
